@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.sarinsa.tomfoolery.common.mob_effect;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;