@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.sarinsa.tomfoolery.datagen.loot_table;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;